# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='school name')),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='school pincode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set([('name', 'pincode')]),
        ),
    ]
