# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTable',
            fields=[
                ('bids', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Bids')),
                ('base_price', models.PositiveIntegerField(verbose_name='Base Price')),
            ],
            options={
                'db_table': 'base_table',
            },
        ),
    ]
