# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_basetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrp', models.PositiveIntegerField(verbose_name='RRP')),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'approved')], max_length=1)),
                ('bids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.BaseTable')),
            ],
            options={
                'db_table': 'test_rrp',
            },
        ),
    ]
