# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_testrrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrrp',
            name='bids',
            field=models.CharField(max_length=20, verbose_name='Bids'),
        ),
    ]
