# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170711_2033'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basetable',
            table='base_price',
        ),
    ]
